//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBootstrapJQueryTutorial_NETFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUPLICATE_EMP
    {
        public int EMPNO { get; set; }
        public string ENAME { get; set; }
        public Nullable<decimal> SAL { get; set; }
        public int DEPTNO { get; set; }
        public Nullable<int> MGRNO { get; set; }
    }
}
