//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBootstrapJQueryTutorial_NETFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using MVCBootstrapJQueryTutorial_NETFramework.Models;

    public partial class MyDatabaseEntities : DbContext
    {
        public MyDatabaseEntities()
            : base("name=MyDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DEPT> DEPTs { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<DUPLICATE_EMP> DUPLICATE_EMP { get; set; }
    }
}
